package exception;

public class Main05 {
	public static void main(String[] args) {

		
		try {
			int[] arr = new int[3];
			for(int i = 0; i<5; i++) {
				arr[i] = i;
				System.out.println(arr[i]);
			}
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("에러발생");
			System.out.println(e.getMessage());
		}
		
		System.out.println("배열출력 : " + arr[2]);
		
	}

}








